//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class PEDIDO
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public PEDIDO()
        {
            this.PAGO = new HashSet<PAGO>();
            this.USUARIO_PEDIDO = new HashSet<USUARIO_PEDIDO>();
        }
    
        public decimal ID_PEDIDO { get; set; }
        public System.DateTime FECHA { get; set; }
        public System.DateTime HORA { get; set; }
        public decimal TOTAL { get; set; }
        public Nullable<decimal> PROPINA { get; set; }
        public decimal MESA_ID_MESA { get; set; }
    
        public virtual DETALLE_PEDIDO DETALLE_PEDIDO { get; set; }
        public virtual MESA MESA { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PAGO> PAGO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<USUARIO_PEDIDO> USUARIO_PEDIDO { get; set; }
    }
}
