//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm
{
    using System;
    using System.Collections.Generic;
    
    public partial class RESERVA
    {
        public decimal ID_RESERVA { get; set; }
        public string CODIGO_RESERVA { get; set; }
        public System.DateTime FECHA { get; set; }
        public decimal CANTIDAD_COMENSALES { get; set; }
        public string ESTADO_RESERVA { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
        public decimal USUARIO_ROL_ID_ROL { get; set; }
        public decimal MESA_ID_MESA { get; set; }
    
        public virtual MESA MESA { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
