# Generated by Django 4.2.8 on 2023-12-14 11:19

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EstPedido',
            fields=[
                ('id_est_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'est_pedido',
            },
        ),
        migrations.CreateModel(
            name='MensajeContacto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=50, verbose_name='Nombre')),
                ('correo_electronico', models.CharField(max_length=50, verbose_name='Correo Electrónico')),
                ('asunto', models.CharField(max_length=50, verbose_name='Asunto')),
                ('mensaje', models.CharField(max_length=500, verbose_name='Mensaje')),
            ],
            options={
                'verbose_name': 'Mensaje de Contacto',
                'db_table': 'MENSAJE_CONTACTO',
            },
        ),
        migrations.CreateModel(
            name='Mesa',
            fields=[
                ('id_mesa', models.BigIntegerField(primary_key=True, serialize=False)),
                ('numero_mesa', models.BigIntegerField()),
                ('capacidad', models.BigIntegerField(blank=True, null=True)),
                ('descripcion', models.CharField(max_length=200)),
                ('en_uso', models.CharField(max_length=1)),
                ('activa', models.CharField(max_length=1)),
            ],
            options={
                'db_table': 'mesa',
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id_pedido', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_hora', models.DateTimeField()),
                ('total', models.BigIntegerField()),
                ('propina', models.BigIntegerField(blank=True, null=True)),
                ('mesa_id_mesa', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mesa_id_mesa', to='home.mesa')),
            ],
            options={
                'db_table': 'pedido',
            },
        ),
        migrations.CreateModel(
            name='Proveedor',
            fields=[
                ('id', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=50)),
                ('email', models.CharField(blank=True, max_length=50, null=True)),
                ('direccion', models.CharField(max_length=50)),
            ],
            options={
                'db_table': 'proveedor',
            },
        ),
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id_receta', models.BigIntegerField(primary_key=True, serialize=False)),
                ('nombre', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=200)),
                ('tiempo_preparacion', models.BigIntegerField()),
                ('precio', models.FloatField()),
                ('foto', models.BinaryField(blank=True, null=True)),
            ],
            options={
                'db_table': 'receta',
            },
        ),
        migrations.CreateModel(
            name='Rol',
            fields=[
                ('id_rol', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'rol',
            },
        ),
        migrations.CreateModel(
            name='Tipo_menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo_menu', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'TIPO_MENU',
            },
        ),
        migrations.CreateModel(
            name='TipoDePago',
            fields=[
                ('id_tipo_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_de_pago',
            },
        ),
        migrations.CreateModel(
            name='TipoProducto',
            fields=[
                ('id_tipo', models.BigIntegerField(primary_key=True, serialize=False)),
                ('tipo_producto', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'tipo_producto',
            },
        ),
        migrations.CreateModel(
            name='UnidadDeMedida',
            fields=[
                ('id_u_medida', models.BigIntegerField(primary_key=True, serialize=False)),
                ('codigo_u_medida', models.CharField(max_length=25)),
                ('descripcion', models.CharField(max_length=25)),
            ],
            options={
                'db_table': 'unidad_de_medida',
            },
        ),
        migrations.CreateModel(
            name='UsuarioPedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comentario_especial', models.CharField(blank=True, max_length=25, null=True)),
                ('pedido_id_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos', to='home.pedido')),
                ('rol_id_rol', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='pedidos_asignados', to='home.rol')),
            ],
            options={
                'db_table': 'usuario_pedido',
            },
        ),
        migrations.CreateModel(
            name='Reserva',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha_reserva', models.DateField(default=django.utils.timezone.now)),
                ('nombre', models.CharField(default='Nombre', max_length=50)),
                ('apellido', models.CharField(default='Apellido', max_length=50)),
                ('cantidad_comensales', models.IntegerField()),
                ('estado_reserva', models.CharField(max_length=20)),
                ('tiempo', models.TimeField(default='00:00')),
                ('comentario', models.CharField(max_length=200)),
                ('mesa', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.mesa')),
                ('user', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'RESERVA',
            },
        ),
        migrations.CreateModel(
            name='Pago',
            fields=[
                ('id_pago', models.BigIntegerField(primary_key=True, serialize=False)),
                ('fecha_pago', models.DateField(blank=True, null=True)),
                ('url', models.CharField(blank=True, max_length=500, null=True)),
                ('token', models.CharField(blank=True, max_length=500, null=True)),
                ('orden_pago', models.BigIntegerField(blank=True, null=True)),
                ('cuotas', models.BigIntegerField(blank=True, null=True)),
                ('pedido_id_pedido', models.ForeignKey(db_column='pedido_id_pedido', on_delete=django.db.models.deletion.DO_NOTHING, to='home.pedido')),
                ('tipo_de_pago_id_tipo_pago', models.ForeignKey(db_column='tipo_de_pago_id_tipo_pago', on_delete=django.db.models.deletion.DO_NOTHING, to='home.tipodepago')),
            ],
            options={
                'db_table': 'pago',
            },
        ),
        migrations.CreateModel(
            name='Menu',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(default=datetime.datetime.now)),
                ('plato', models.CharField(max_length=20)),
                ('descripcion', models.CharField(max_length=200)),
                ('imagen', models.ImageField(null=True, upload_to='Menu')),
                ('tipo_menu', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='home.tipo_menu')),
            ],
            options={
                'db_table': 'MENU',
            },
        ),
        migrations.CreateModel(
            name='Empleado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=50)),
                ('region', models.CharField(default='Región Metropolitana', max_length=50)),
                ('comuna', models.CharField(default='Santiago', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('charge', models.CharField(max_length=50)),
                ('apartament', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'EMPLEADO',
            },
        ),
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('adress', models.CharField(max_length=50)),
                ('region', models.CharField(default='Región Metropolitana', max_length=50)),
                ('comuna', models.CharField(default='Santiago', max_length=50)),
                ('phone', models.CharField(max_length=50)),
                ('user', models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'CLIENTE',
            },
        ),
        migrations.CreateModel(
            name='Usuario',
            fields=[
                ('id_usuario', models.BigIntegerField(primary_key=True, serialize=False)),
                ('contrasena', models.CharField(max_length=150)),
                ('nombre', models.CharField(max_length=30)),
                ('apellido', models.CharField(max_length=30)),
                ('email', models.CharField(max_length=100)),
                ('direccion', models.CharField(blank=True, max_length=100, null=True)),
                ('estado_usuario', models.CharField(max_length=1)),
                ('telefono', models.CharField(blank=True, max_length=25, null=True)),
                ('genero', models.CharField(blank=True, max_length=25, null=True)),
                ('rol_id_rol', models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='home.rol')),
            ],
            options={
                'db_table': 'usuario',
                'unique_together': {('id_usuario', 'rol_id_rol')},
            },
        ),
        migrations.CreateModel(
            name='Producto',
            fields=[
                ('id_producto', models.BigIntegerField(primary_key=True, serialize=False)),
                ('descripcion', models.CharField(max_length=150)),
                ('precio_compra', models.FloatField()),
                ('precio_venta', models.FloatField()),
                ('nombre', models.CharField(max_length=100)),
                ('marca', models.CharField(blank=True, max_length=25, null=True)),
                ('categoria', models.CharField(max_length=25)),
                ('stock', models.BigIntegerField()),
                ('fecha_vencimiento', models.DateField()),
                ('proveedor', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to='home.proveedor')),
                ('tipo_producto_id_tipo', models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, related_name='tipo_producto_id_tipo', to='home.tipoproducto')),
                ('unidad_de_medida_id_u_medida', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='unidad_de_medida_id_u_medida', to='home.unidaddemedida')),
            ],
            options={
                'db_table': 'producto',
                'unique_together': {('id_producto', 'unidad_de_medida_id_u_medida', 'tipo_producto_id_tipo')},
            },
        ),
        migrations.CreateModel(
            name='DetallePedido',
            fields=[
                ('descripcion', models.CharField(max_length=100)),
                ('cantidad', models.BigIntegerField()),
                ('pedido_id_pedido', models.OneToOneField(on_delete=django.db.models.deletion.DO_NOTHING, primary_key=True, related_name='pedido_id_pedido', serialize=False, to='home.pedido')),
                ('est_pedido_id_est_pedido', models.ForeignKey(on_delete=django.db.models.deletion.DO_NOTHING, related_name='est_pedido_id_est_pedido', to='home.estpedido')),
                ('producto_id_producto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_id_producto', to='home.producto')),
                ('producto_id_tipo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_id_tipo', to='home.producto')),
                ('producto_id_u_medida', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='producto_id_u_medida', to='home.producto')),
                ('receta_id_receta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='receta_id_receta', to='home.receta')),
                ('user_id_usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='user_id_usuario', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'detalle_pedido',
            },
        ),
    ]
