//------------------------------------------------------------------------------
// <auto-generated>
//     Este código fue generado por una herramienta.
//     Versión de runtime:4.0.30319.42000
//
//     Los cambios en este archivo podrían causar un comportamiento incorrecto y se perderán si
//     se vuelve a generar el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WPF_LoginForm.ServiceReference1 {
    
    
    /// <remarks/>
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.Xml", "4.8.9037.0")]
    [System.SerializableAttribute()]
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.ComponentModel.DesignerCategoryAttribute("code")]
    [System.Xml.Serialization.XmlTypeAttribute(Namespace="http://WebServices/")]
    public partial class Exception : object, System.ComponentModel.INotifyPropertyChanged {
        
        private string messageField;
        
        /// <remarks/>
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified, Order=0)]
        public string message {
            get {
                return this.messageField;
            }
            set {
                this.messageField = value;
                this.RaisePropertyChanged("message");
            }
        }
        
        public event System.ComponentModel.PropertyChangedEventHandler PropertyChanged;
        
        protected void RaisePropertyChanged(string propertyName) {
            System.ComponentModel.PropertyChangedEventHandler propertyChanged = this.PropertyChanged;
            if ((propertyChanged != null)) {
                propertyChanged(this, new System.ComponentModel.PropertyChangedEventArgs(propertyName));
            }
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ServiceModel.ServiceContractAttribute(Namespace="http://WebServices/", ConfigurationName="ServiceReference1.WebServiceOkcasa")]
    public interface WebServiceOkcasa {
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/LoginRequest", ReplyAction="http://WebServices/WebServiceOkcasa/LoginResponse")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPF_LoginForm.ServiceReference1.Exception), Action="http://WebServices/WebServiceOkcasa/Login/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.LoginResponse Login(WPF_LoginForm.ServiceReference1.LoginRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/LoginRequest", ReplyAction="http://WebServices/WebServiceOkcasa/LoginResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginResponse> LoginAsync(WPF_LoginForm.ServiceReference1.LoginRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteClienteRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteClienteResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.ExisteClienteResponse ExisteCliente(WPF_LoginForm.ServiceReference1.ExisteClienteRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteClienteRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteClienteResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteClienteResponse> ExisteClienteAsync(WPF_LoginForm.ServiceReference1.ExisteClienteRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteInspeccionRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteInspeccionResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse ExisteInspeccion(WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteInspeccionRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteInspeccionResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse> ExisteInspeccionAsync(WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/helloRequest", ReplyAction="http://WebServices/WebServiceOkcasa/helloResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.helloResponse hello(WPF_LoginForm.ServiceReference1.helloRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/helloRequest", ReplyAction="http://WebServices/WebServiceOkcasa/helloResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.helloResponse> helloAsync(WPF_LoginForm.ServiceReference1.helloRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/Login2Request", ReplyAction="http://WebServices/WebServiceOkcasa/Login2Response")]
        [System.ServiceModel.FaultContractAttribute(typeof(WPF_LoginForm.ServiceReference1.Exception), Action="http://WebServices/WebServiceOkcasa/Login2/Fault/Exception", Name="Exception")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.Login2Response Login2(WPF_LoginForm.ServiceReference1.Login2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/Login2Request", ReplyAction="http://WebServices/WebServiceOkcasa/Login2Response")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.Login2Response> Login2Async(WPF_LoginForm.ServiceReference1.Login2Request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/LoginPeruanoRequest", ReplyAction="http://WebServices/WebServiceOkcasa/LoginPeruanoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.LoginPeruanoResponse LoginPeruano(WPF_LoginForm.ServiceReference1.LoginPeruanoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/LoginPeruanoRequest", ReplyAction="http://WebServices/WebServiceOkcasa/LoginPeruanoResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginPeruanoResponse> LoginPeruanoAsync(WPF_LoginForm.ServiceReference1.LoginPeruanoRequest request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteCliente2Request", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteCliente2Response")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.ExisteCliente2Response ExisteCliente2(WPF_LoginForm.ServiceReference1.ExisteCliente2Request request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteCliente2Request", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteCliente2Response")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteCliente2Response> ExisteCliente2Async(WPF_LoginForm.ServiceReference1.ExisteCliente2Request request);
        
        // CODEGEN: El parámetro 'return' requiere información adicional de esquema que no se puede capturar con el modo de parámetros. El atributo específico es 'System.Xml.Serialization.XmlElementAttribute'.
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteEquipoRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteEquipoResponse")]
        [System.ServiceModel.XmlSerializerFormatAttribute(SupportFaults=true)]
        [return: System.ServiceModel.MessageParameterAttribute(Name="return")]
        WPF_LoginForm.ServiceReference1.ExisteEquipoResponse ExisteEquipo(WPF_LoginForm.ServiceReference1.ExisteEquipoRequest request);
        
        [System.ServiceModel.OperationContractAttribute(Action="http://WebServices/WebServiceOkcasa/ExisteEquipoRequest", ReplyAction="http://WebServices/WebServiceOkcasa/ExisteEquipoResponse")]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteEquipoResponse> ExisteEquipoAsync(WPF_LoginForm.ServiceReference1.ExisteEquipoRequest request);
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class LoginRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public LoginRequest() {
        }
        
        public LoginRequest(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class LoginResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int @return;
        
        public LoginResponse() {
        }
        
        public LoginResponse(int @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteCliente", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteClienteRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string nombre;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string apellido;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=2)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idcliente;
        
        public ExisteClienteRequest() {
        }
        
        public ExisteClienteRequest(string nombre, string apellido, int idcliente) {
            this.nombre = nombre;
            this.apellido = apellido;
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteClienteResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteClienteResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExisteClienteResponse() {
        }
        
        public ExisteClienteResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteInspeccion", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteInspeccionRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idinspeccion;
        
        public ExisteInspeccionRequest() {
        }
        
        public ExisteInspeccionRequest(int idinspeccion) {
            this.idinspeccion = idinspeccion;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteInspeccionResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteInspeccionResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExisteInspeccionResponse() {
        }
        
        public ExisteInspeccionResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="hello", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class helloRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string name;
        
        public helloRequest() {
        }
        
        public helloRequest(string name) {
            this.name = name;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="helloResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class helloResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string @return;
        
        public helloResponse() {
        }
        
        public helloResponse(string @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class Login2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public Login2Request() {
        }
        
        public Login2Request(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="Login2Response", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class Login2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public Login2Response() {
        }
        
        public Login2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPeruano", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class LoginPeruanoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string user;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string pass;
        
        public LoginPeruanoRequest() {
        }
        
        public LoginPeruanoRequest(string user, string pass) {
            this.user = user;
            this.pass = pass;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="LoginPeruanoResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class LoginPeruanoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public LoginPeruanoResponse() {
        }
        
        public LoginPeruanoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteCliente2", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteCliente2Request {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public string rut;
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=1)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idcliente;
        
        public ExisteCliente2Request() {
        }
        
        public ExisteCliente2Request(string rut, int idcliente) {
            this.rut = rut;
            this.idcliente = idcliente;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteCliente2Response", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteCliente2Response {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExisteCliente2Response() {
        }
        
        public ExisteCliente2Response(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteEquipo", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteEquipoRequest {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public int idequipo;
        
        public ExisteEquipoRequest() {
        }
        
        public ExisteEquipoRequest(int idequipo) {
            this.idequipo = idequipo;
        }
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
    [System.ServiceModel.MessageContractAttribute(WrapperName="ExisteEquipoResponse", WrapperNamespace="http://WebServices/", IsWrapped=true)]
    public partial class ExisteEquipoResponse {
        
        [System.ServiceModel.MessageBodyMemberAttribute(Namespace="http://WebServices/", Order=0)]
        [System.Xml.Serialization.XmlElementAttribute(Form=System.Xml.Schema.XmlSchemaForm.Unqualified)]
        public bool @return;
        
        public ExisteEquipoResponse() {
        }
        
        public ExisteEquipoResponse(bool @return) {
            this.@return = @return;
        }
    }
    
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public interface WebServiceOkcasaChannel : WPF_LoginForm.ServiceReference1.WebServiceOkcasa, System.ServiceModel.IClientChannel {
    }
    
    [System.Diagnostics.DebuggerStepThroughAttribute()]
    [System.CodeDom.Compiler.GeneratedCodeAttribute("System.ServiceModel", "4.0.0.0")]
    public partial class WebServiceOkcasaClient : System.ServiceModel.ClientBase<WPF_LoginForm.ServiceReference1.WebServiceOkcasa>, WPF_LoginForm.ServiceReference1.WebServiceOkcasa {
        
        public WebServiceOkcasaClient() {
        }
        
        public WebServiceOkcasaClient(string endpointConfigurationName) : 
                base(endpointConfigurationName) {
        }
        
        public WebServiceOkcasaClient(string endpointConfigurationName, string remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOkcasaClient(string endpointConfigurationName, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(endpointConfigurationName, remoteAddress) {
        }
        
        public WebServiceOkcasaClient(System.ServiceModel.Channels.Binding binding, System.ServiceModel.EndpointAddress remoteAddress) : 
                base(binding, remoteAddress) {
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.LoginResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.Login(WPF_LoginForm.ServiceReference1.LoginRequest request) {
            return base.Channel.Login(request);
        }
        
        public int Login(string user, string pass) {
            WPF_LoginForm.ServiceReference1.LoginRequest inValue = new WPF_LoginForm.ServiceReference1.LoginRequest();
            inValue.user = user;
            inValue.pass = pass;
            WPF_LoginForm.ServiceReference1.LoginResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).Login(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.LoginAsync(WPF_LoginForm.ServiceReference1.LoginRequest request) {
            return base.Channel.LoginAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginResponse> LoginAsync(string user, string pass) {
            WPF_LoginForm.ServiceReference1.LoginRequest inValue = new WPF_LoginForm.ServiceReference1.LoginRequest();
            inValue.user = user;
            inValue.pass = pass;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).LoginAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.ExisteClienteResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteCliente(WPF_LoginForm.ServiceReference1.ExisteClienteRequest request) {
            return base.Channel.ExisteCliente(request);
        }
        
        public bool ExisteCliente(string nombre, string apellido, int idcliente) {
            WPF_LoginForm.ServiceReference1.ExisteClienteRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteClienteRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.idcliente = idcliente;
            WPF_LoginForm.ServiceReference1.ExisteClienteResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteCliente(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteClienteResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteClienteAsync(WPF_LoginForm.ServiceReference1.ExisteClienteRequest request) {
            return base.Channel.ExisteClienteAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteClienteResponse> ExisteClienteAsync(string nombre, string apellido, int idcliente) {
            WPF_LoginForm.ServiceReference1.ExisteClienteRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteClienteRequest();
            inValue.nombre = nombre;
            inValue.apellido = apellido;
            inValue.idcliente = idcliente;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteClienteAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteInspeccion(WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest request) {
            return base.Channel.ExisteInspeccion(request);
        }
        
        public bool ExisteInspeccion(int idinspeccion) {
            WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest();
            inValue.idinspeccion = idinspeccion;
            WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteInspeccion(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteInspeccionAsync(WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest request) {
            return base.Channel.ExisteInspeccionAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteInspeccionResponse> ExisteInspeccionAsync(int idinspeccion) {
            WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteInspeccionRequest();
            inValue.idinspeccion = idinspeccion;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteInspeccionAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.helloResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.hello(WPF_LoginForm.ServiceReference1.helloRequest request) {
            return base.Channel.hello(request);
        }
        
        public string hello(string name) {
            WPF_LoginForm.ServiceReference1.helloRequest inValue = new WPF_LoginForm.ServiceReference1.helloRequest();
            inValue.name = name;
            WPF_LoginForm.ServiceReference1.helloResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).hello(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.helloResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.helloAsync(WPF_LoginForm.ServiceReference1.helloRequest request) {
            return base.Channel.helloAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.helloResponse> helloAsync(string name) {
            WPF_LoginForm.ServiceReference1.helloRequest inValue = new WPF_LoginForm.ServiceReference1.helloRequest();
            inValue.name = name;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).helloAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.Login2Response WPF_LoginForm.ServiceReference1.WebServiceOkcasa.Login2(WPF_LoginForm.ServiceReference1.Login2Request request) {
            return base.Channel.Login2(request);
        }
        
        public bool Login2(string user, string pass) {
            WPF_LoginForm.ServiceReference1.Login2Request inValue = new WPF_LoginForm.ServiceReference1.Login2Request();
            inValue.user = user;
            inValue.pass = pass;
            WPF_LoginForm.ServiceReference1.Login2Response retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).Login2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.Login2Response> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.Login2Async(WPF_LoginForm.ServiceReference1.Login2Request request) {
            return base.Channel.Login2Async(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.Login2Response> Login2Async(string user, string pass) {
            WPF_LoginForm.ServiceReference1.Login2Request inValue = new WPF_LoginForm.ServiceReference1.Login2Request();
            inValue.user = user;
            inValue.pass = pass;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).Login2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.LoginPeruanoResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.LoginPeruano(WPF_LoginForm.ServiceReference1.LoginPeruanoRequest request) {
            return base.Channel.LoginPeruano(request);
        }
        
        public bool LoginPeruano(string user, string pass) {
            WPF_LoginForm.ServiceReference1.LoginPeruanoRequest inValue = new WPF_LoginForm.ServiceReference1.LoginPeruanoRequest();
            inValue.user = user;
            inValue.pass = pass;
            WPF_LoginForm.ServiceReference1.LoginPeruanoResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).LoginPeruano(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginPeruanoResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.LoginPeruanoAsync(WPF_LoginForm.ServiceReference1.LoginPeruanoRequest request) {
            return base.Channel.LoginPeruanoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.LoginPeruanoResponse> LoginPeruanoAsync(string user, string pass) {
            WPF_LoginForm.ServiceReference1.LoginPeruanoRequest inValue = new WPF_LoginForm.ServiceReference1.LoginPeruanoRequest();
            inValue.user = user;
            inValue.pass = pass;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).LoginPeruanoAsync(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.ExisteCliente2Response WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteCliente2(WPF_LoginForm.ServiceReference1.ExisteCliente2Request request) {
            return base.Channel.ExisteCliente2(request);
        }
        
        public bool ExisteCliente2(string rut, int idcliente) {
            WPF_LoginForm.ServiceReference1.ExisteCliente2Request inValue = new WPF_LoginForm.ServiceReference1.ExisteCliente2Request();
            inValue.rut = rut;
            inValue.idcliente = idcliente;
            WPF_LoginForm.ServiceReference1.ExisteCliente2Response retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteCliente2(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteCliente2Response> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteCliente2Async(WPF_LoginForm.ServiceReference1.ExisteCliente2Request request) {
            return base.Channel.ExisteCliente2Async(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteCliente2Response> ExisteCliente2Async(string rut, int idcliente) {
            WPF_LoginForm.ServiceReference1.ExisteCliente2Request inValue = new WPF_LoginForm.ServiceReference1.ExisteCliente2Request();
            inValue.rut = rut;
            inValue.idcliente = idcliente;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteCliente2Async(inValue);
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        WPF_LoginForm.ServiceReference1.ExisteEquipoResponse WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteEquipo(WPF_LoginForm.ServiceReference1.ExisteEquipoRequest request) {
            return base.Channel.ExisteEquipo(request);
        }
        
        public bool ExisteEquipo(int idequipo) {
            WPF_LoginForm.ServiceReference1.ExisteEquipoRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteEquipoRequest();
            inValue.idequipo = idequipo;
            WPF_LoginForm.ServiceReference1.ExisteEquipoResponse retVal = ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteEquipo(inValue);
            return retVal.@return;
        }
        
        [System.ComponentModel.EditorBrowsableAttribute(System.ComponentModel.EditorBrowsableState.Advanced)]
        System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteEquipoResponse> WPF_LoginForm.ServiceReference1.WebServiceOkcasa.ExisteEquipoAsync(WPF_LoginForm.ServiceReference1.ExisteEquipoRequest request) {
            return base.Channel.ExisteEquipoAsync(request);
        }
        
        public System.Threading.Tasks.Task<WPF_LoginForm.ServiceReference1.ExisteEquipoResponse> ExisteEquipoAsync(int idequipo) {
            WPF_LoginForm.ServiceReference1.ExisteEquipoRequest inValue = new WPF_LoginForm.ServiceReference1.ExisteEquipoRequest();
            inValue.idequipo = idequipo;
            return ((WPF_LoginForm.ServiceReference1.WebServiceOkcasa)(this)).ExisteEquipoAsync(inValue);
        }
    }
}
