//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DETALLE_PEDIDO
    {
        public string DESCRIPCION { get; set; }
        public decimal CANTIDAD { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
        public Nullable<decimal> RECETA_ID_RECETA { get; set; }
        public Nullable<decimal> PRODUCTO_ID_PRODUCTO { get; set; }
        public Nullable<decimal> PRODUCTO_ID_U_MEDIDA { get; set; }
        public Nullable<decimal> PRODUCTO_ID_TIPO { get; set; }
        public decimal EST_PEDIDO_ID_EST_PEDIDO { get; set; }
    
        public virtual EST_PEDIDO EST_PEDIDO { get; set; }
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual PRODUCTO PRODUCTO { get; set; }
        public virtual RECETA RECETA { get; set; }
    }
}
