//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class MENU
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public MENU()
        {
            this.PRODUCTO = new HashSet<PRODUCTO>();
            this.RECETA = new HashSet<RECETA>();
        }
    
        public decimal ID_MENU { get; set; }
        public string CODIGO_MENU { get; set; }
        public string NOMBRE { get; set; }
        public decimal PRECIO { get; set; }
        public byte[] FOTO { get; set; }
        public bool DISPONIBLE { get; set; }
        public decimal TIPO_MENU_ID_TIPO_MENU { get; set; }
    
        public virtual TIPO_MENU TIPO_MENU { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<PRODUCTO> PRODUCTO { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<RECETA> RECETA { get; set; }
    }
}
