//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class RestauranteEntities : DbContext
    {
        public RestauranteEntities()
            : base("name=RestauranteEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<DETALLE_PEDIDO> DETALLE_PEDIDO { get; set; }
        public virtual DbSet<EST_PEDIDO> EST_PEDIDO { get; set; }
        public virtual DbSet<MENU> MENU { get; set; }
        public virtual DbSet<MESA> MESA { get; set; }
        public virtual DbSet<PAGO> PAGO { get; set; }
        public virtual DbSet<PEDIDO> PEDIDO { get; set; }
        public virtual DbSet<PRODUCTO> PRODUCTO { get; set; }
        public virtual DbSet<PROVEEDOR> PROVEEDOR { get; set; }
        public virtual DbSet<RECETA> RECETA { get; set; }
        public virtual DbSet<RESERVA> RESERVA { get; set; }
        public virtual DbSet<ROL> ROL { get; set; }
        public virtual DbSet<TIPO_DE_PAGO> TIPO_DE_PAGO { get; set; }
        public virtual DbSet<TIPO_MENU> TIPO_MENU { get; set; }
        public virtual DbSet<TIPO_PRODUCTO> TIPO_PRODUCTO { get; set; }
        public virtual DbSet<UNIDAD_DE_MEDIDA> UNIDAD_DE_MEDIDA { get; set; }
        public virtual DbSet<USUARIO> USUARIO { get; set; }
        public virtual DbSet<PRODUCTO_RECETA> PRODUCTO_RECETA { get; set; }
        public virtual DbSet<USUARIO_PEDIDO> USUARIO_PEDIDO { get; set; }
    
        public virtual int AGREGARDETALLEPEDIDO(string p_DESCRIPCION, Nullable<decimal> p_CANTIDAD, Nullable<decimal> p_PEDIDO_ID_PEDIDO, Nullable<decimal> p_RECETA_ID_RECETA, Nullable<decimal> p_PRODUCTO_ID_PRODUCTO, Nullable<decimal> p_PRODUCTO_ID_U_MEDIDA, Nullable<decimal> p_PRODUCTO_ID_TIPO, Nullable<decimal> p_EST_PEDIDO_ID_EST_PEDIDO)
        {
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_CANTIDADParameter = p_CANTIDAD.HasValue ?
                new ObjectParameter("P_CANTIDAD", p_CANTIDAD) :
                new ObjectParameter("P_CANTIDAD", typeof(decimal));
    
            var p_PEDIDO_ID_PEDIDOParameter = p_PEDIDO_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", p_PEDIDO_ID_PEDIDO) :
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", typeof(decimal));
    
            var p_RECETA_ID_RECETAParameter = p_RECETA_ID_RECETA.HasValue ?
                new ObjectParameter("P_RECETA_ID_RECETA", p_RECETA_ID_RECETA) :
                new ObjectParameter("P_RECETA_ID_RECETA", typeof(decimal));
    
            var p_PRODUCTO_ID_PRODUCTOParameter = p_PRODUCTO_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_PRODUCTO_ID_PRODUCTO", p_PRODUCTO_ID_PRODUCTO) :
                new ObjectParameter("P_PRODUCTO_ID_PRODUCTO", typeof(decimal));
    
            var p_PRODUCTO_ID_U_MEDIDAParameter = p_PRODUCTO_ID_U_MEDIDA.HasValue ?
                new ObjectParameter("P_PRODUCTO_ID_U_MEDIDA", p_PRODUCTO_ID_U_MEDIDA) :
                new ObjectParameter("P_PRODUCTO_ID_U_MEDIDA", typeof(decimal));
    
            var p_PRODUCTO_ID_TIPOParameter = p_PRODUCTO_ID_TIPO.HasValue ?
                new ObjectParameter("P_PRODUCTO_ID_TIPO", p_PRODUCTO_ID_TIPO) :
                new ObjectParameter("P_PRODUCTO_ID_TIPO", typeof(decimal));
    
            var p_EST_PEDIDO_ID_EST_PEDIDOParameter = p_EST_PEDIDO_ID_EST_PEDIDO.HasValue ?
                new ObjectParameter("P_EST_PEDIDO_ID_EST_PEDIDO", p_EST_PEDIDO_ID_EST_PEDIDO) :
                new ObjectParameter("P_EST_PEDIDO_ID_EST_PEDIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("AGREGARDETALLEPEDIDO", p_DESCRIPCIONParameter, p_CANTIDADParameter, p_PEDIDO_ID_PEDIDOParameter, p_RECETA_ID_RECETAParameter, p_PRODUCTO_ID_PRODUCTOParameter, p_PRODUCTO_ID_U_MEDIDAParameter, p_PRODUCTO_ID_TIPOParameter, p_EST_PEDIDO_ID_EST_PEDIDOParameter);
        }
    
        public virtual int ASIGNARMESAACLIENTE(Nullable<decimal> p_ID_MESA, string p_CLIENTE_NOMBRE)
        {
            var p_ID_MESAParameter = p_ID_MESA.HasValue ?
                new ObjectParameter("P_ID_MESA", p_ID_MESA) :
                new ObjectParameter("P_ID_MESA", typeof(decimal));
    
            var p_CLIENTE_NOMBREParameter = p_CLIENTE_NOMBRE != null ?
                new ObjectParameter("P_CLIENTE_NOMBRE", p_CLIENTE_NOMBRE) :
                new ObjectParameter("P_CLIENTE_NOMBRE", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ASIGNARMESAACLIENTE", p_ID_MESAParameter, p_CLIENTE_NOMBREParameter);
        }
    
        public virtual int CANTIDADPRODUCTOSPORCATEGORIA()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CANTIDADPRODUCTOSPORCATEGORIA");
        }
    
        public virtual int CONTROLARSTOCK(Nullable<decimal> p_ID_PRODUCTO, Nullable<decimal> p_CANTIDAD_VENTA)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            var p_CANTIDAD_VENTAParameter = p_CANTIDAD_VENTA.HasValue ?
                new ObjectParameter("P_CANTIDAD_VENTA", p_CANTIDAD_VENTA) :
                new ObjectParameter("P_CANTIDAD_VENTA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("CONTROLARSTOCK", p_ID_PRODUCTOParameter, p_CANTIDAD_VENTAParameter);
        }
    
        public virtual int DASHBOARDDATOS(ObjectParameter tOTVENTAS, ObjectParameter nPRODUCTO, ObjectParameter nPROVEEDORES, ObjectParameter nPEDIDO, ObjectParameter nTRABAJADORES, ObjectParameter nCLIENTES)
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("DASHBOARDDATOS", tOTVENTAS, nPRODUCTO, nPROVEEDORES, nPEDIDO, nTRABAJADORES, nCLIENTES);
        }
    
        public virtual int ELIMINARMENU(Nullable<decimal> p_ID_MENU)
        {
            var p_ID_MENUParameter = p_ID_MENU.HasValue ?
                new ObjectParameter("P_ID_MENU", p_ID_MENU) :
                new ObjectParameter("P_ID_MENU", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARMENU", p_ID_MENUParameter);
        }
    
        public virtual int ELIMINARMESA(Nullable<decimal> p_ID_MESA)
        {
            var p_ID_MESAParameter = p_ID_MESA.HasValue ?
                new ObjectParameter("P_ID_MESA", p_ID_MESA) :
                new ObjectParameter("P_ID_MESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARMESA", p_ID_MESAParameter);
        }
    
        public virtual int ELIMINARPAGO(Nullable<decimal> p_ID_PAGO)
        {
            var p_ID_PAGOParameter = p_ID_PAGO.HasValue ?
                new ObjectParameter("P_ID_PAGO", p_ID_PAGO) :
                new ObjectParameter("P_ID_PAGO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARPAGO", p_ID_PAGOParameter);
        }
    
        public virtual int ELIMINARPRODUCTO(Nullable<decimal> p_ID_PRODUCTO)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARPRODUCTO", p_ID_PRODUCTOParameter);
        }
    
        public virtual int ELIMINARPROVEEDOR(Nullable<decimal> p_ID)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARPROVEEDOR", p_IDParameter);
        }
    
        public virtual int ELIMINARRECETA(Nullable<decimal> p_ID_RECETA)
        {
            var p_ID_RECETAParameter = p_ID_RECETA.HasValue ?
                new ObjectParameter("P_ID_RECETA", p_ID_RECETA) :
                new ObjectParameter("P_ID_RECETA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARRECETA", p_ID_RECETAParameter);
        }
    
        public virtual int ELIMINARRESERVA(Nullable<decimal> p_ID_RESERVA)
        {
            var p_ID_RESERVAParameter = p_ID_RESERVA.HasValue ?
                new ObjectParameter("P_ID_RESERVA", p_ID_RESERVA) :
                new ObjectParameter("P_ID_RESERVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARRESERVA", p_ID_RESERVAParameter);
        }
    
        public virtual int ELIMINARRESERVACONUSUARIO(Nullable<decimal> p_ID_RESERVA)
        {
            var p_ID_RESERVAParameter = p_ID_RESERVA.HasValue ?
                new ObjectParameter("P_ID_RESERVA", p_ID_RESERVA) :
                new ObjectParameter("P_ID_RESERVA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARRESERVACONUSUARIO", p_ID_RESERVAParameter);
        }
    
        public virtual int ELIMINARUSUARIO(Nullable<decimal> p_ID_USUARIO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("ELIMINARUSUARIO", p_ID_USUARIOParameter);
        }
    
        public virtual int INGRESARRECETA(Nullable<decimal> p_ID_RECETA, string p_NOMBRE, string p_DESCRIPCION, Nullable<decimal> p_TIEMPO_PREPARACION, Nullable<decimal> p_PRECIO)
        {
            var p_ID_RECETAParameter = p_ID_RECETA.HasValue ?
                new ObjectParameter("P_ID_RECETA", p_ID_RECETA) :
                new ObjectParameter("P_ID_RECETA", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESARRECETA", p_ID_RECETAParameter, p_NOMBREParameter, p_DESCRIPCIONParameter, p_TIEMPO_PREPARACIONParameter, p_PRECIOParameter);
        }
    
        public virtual int INGRESARRECETA2(string p_NOMBRE, string p_DESCRIPCION, Nullable<decimal> p_TIEMPO_PREPARACION, Nullable<decimal> p_PRECIO)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESARRECETA2", p_NOMBREParameter, p_DESCRIPCIONParameter, p_TIEMPO_PREPARACIONParameter, p_PRECIOParameter);
        }
    
        public virtual int INGRESARRECETA3(string p_NOMBRE, string p_DESCRIPCION, Nullable<decimal> p_TIEMPO_PREPARACION, Nullable<decimal> p_PRECIO)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INGRESARRECETA3", p_NOMBREParameter, p_DESCRIPCIONParameter, p_TIEMPO_PREPARACIONParameter, p_PRECIOParameter);
        }
    
        public virtual int INSERTARMENU(Nullable<decimal> p_ID_MENU, string p_CODIGO_MENU, string p_NOMBRE, Nullable<decimal> p_PRECIO, byte[] p_FOTO, Nullable<decimal> p_DISPONIBLE, Nullable<decimal> p_TIPO_MENU_ID)
        {
            var p_ID_MENUParameter = p_ID_MENU.HasValue ?
                new ObjectParameter("P_ID_MENU", p_ID_MENU) :
                new ObjectParameter("P_ID_MENU", typeof(decimal));
    
            var p_CODIGO_MENUParameter = p_CODIGO_MENU != null ?
                new ObjectParameter("P_CODIGO_MENU", p_CODIGO_MENU) :
                new ObjectParameter("P_CODIGO_MENU", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_FOTOParameter = p_FOTO != null ?
                new ObjectParameter("P_FOTO", p_FOTO) :
                new ObjectParameter("P_FOTO", typeof(byte[]));
    
            var p_DISPONIBLEParameter = p_DISPONIBLE.HasValue ?
                new ObjectParameter("P_DISPONIBLE", p_DISPONIBLE) :
                new ObjectParameter("P_DISPONIBLE", typeof(decimal));
    
            var p_TIPO_MENU_IDParameter = p_TIPO_MENU_ID.HasValue ?
                new ObjectParameter("P_TIPO_MENU_ID", p_TIPO_MENU_ID) :
                new ObjectParameter("P_TIPO_MENU_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARMENU", p_ID_MENUParameter, p_CODIGO_MENUParameter, p_NOMBREParameter, p_PRECIOParameter, p_FOTOParameter, p_DISPONIBLEParameter, p_TIPO_MENU_IDParameter);
        }
    
        public virtual int INSERTARMESA(Nullable<decimal> p_ID_MESA, Nullable<decimal> p_NUMERO_MESA, Nullable<decimal> p_CAPACIDAD, string p_DESCRIPCION, string p_EN_USO, string p_ACTIVA)
        {
            var p_ID_MESAParameter = p_ID_MESA.HasValue ?
                new ObjectParameter("P_ID_MESA", p_ID_MESA) :
                new ObjectParameter("P_ID_MESA", typeof(decimal));
    
            var p_NUMERO_MESAParameter = p_NUMERO_MESA.HasValue ?
                new ObjectParameter("P_NUMERO_MESA", p_NUMERO_MESA) :
                new ObjectParameter("P_NUMERO_MESA", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_EN_USOParameter = p_EN_USO != null ?
                new ObjectParameter("P_EN_USO", p_EN_USO) :
                new ObjectParameter("P_EN_USO", typeof(string));
    
            var p_ACTIVAParameter = p_ACTIVA != null ?
                new ObjectParameter("P_ACTIVA", p_ACTIVA) :
                new ObjectParameter("P_ACTIVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARMESA", p_ID_MESAParameter, p_NUMERO_MESAParameter, p_CAPACIDADParameter, p_DESCRIPCIONParameter, p_EN_USOParameter, p_ACTIVAParameter);
        }
    
        public virtual int INSERTARPAGO(Nullable<decimal> p_ID_PAGO, Nullable<System.DateTime> p_FECHA_PAGO, string p_URL, string p_TOKEN, Nullable<decimal> p_ORDEN_PAGO, Nullable<decimal> p_TIPO_DE_PAGO_ID_TIPO_PAGO, Nullable<decimal> p_PEDIDO_ID_PEDIDO, Nullable<decimal> p_CUOTAS)
        {
            var p_ID_PAGOParameter = p_ID_PAGO.HasValue ?
                new ObjectParameter("P_ID_PAGO", p_ID_PAGO) :
                new ObjectParameter("P_ID_PAGO", typeof(decimal));
    
            var p_FECHA_PAGOParameter = p_FECHA_PAGO.HasValue ?
                new ObjectParameter("P_FECHA_PAGO", p_FECHA_PAGO) :
                new ObjectParameter("P_FECHA_PAGO", typeof(System.DateTime));
    
            var p_URLParameter = p_URL != null ?
                new ObjectParameter("P_URL", p_URL) :
                new ObjectParameter("P_URL", typeof(string));
    
            var p_TOKENParameter = p_TOKEN != null ?
                new ObjectParameter("P_TOKEN", p_TOKEN) :
                new ObjectParameter("P_TOKEN", typeof(string));
    
            var p_ORDEN_PAGOParameter = p_ORDEN_PAGO.HasValue ?
                new ObjectParameter("P_ORDEN_PAGO", p_ORDEN_PAGO) :
                new ObjectParameter("P_ORDEN_PAGO", typeof(decimal));
    
            var p_TIPO_DE_PAGO_ID_TIPO_PAGOParameter = p_TIPO_DE_PAGO_ID_TIPO_PAGO.HasValue ?
                new ObjectParameter("P_TIPO_DE_PAGO_ID_TIPO_PAGO", p_TIPO_DE_PAGO_ID_TIPO_PAGO) :
                new ObjectParameter("P_TIPO_DE_PAGO_ID_TIPO_PAGO", typeof(decimal));
    
            var p_PEDIDO_ID_PEDIDOParameter = p_PEDIDO_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", p_PEDIDO_ID_PEDIDO) :
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", typeof(decimal));
    
            var p_CUOTASParameter = p_CUOTAS.HasValue ?
                new ObjectParameter("P_CUOTAS", p_CUOTAS) :
                new ObjectParameter("P_CUOTAS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARPAGO", p_ID_PAGOParameter, p_FECHA_PAGOParameter, p_URLParameter, p_TOKENParameter, p_ORDEN_PAGOParameter, p_TIPO_DE_PAGO_ID_TIPO_PAGOParameter, p_PEDIDO_ID_PEDIDOParameter, p_CUOTASParameter);
        }
    
        public virtual int INSERTARPRODUCTO(Nullable<decimal> p_ID_PRODUCTO, string p_DESCRIPCION, Nullable<decimal> p_PRECIO_COMPRA, Nullable<decimal> p_PRECIO_VENTA, string p_NOMBRE, string p_MARCA, string p_CATEGORIA, Nullable<decimal> p_STOCK, Nullable<System.DateTime> p_FECHA_VENCIMIENTO, Nullable<decimal> p_UNIDAD_DE_MEDIDA_ID, Nullable<decimal> p_TIPO_PRODUCTO_ID, Nullable<decimal> p_PROVEEDOR_ID)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_PRECIO_COMPRAParameter = p_PRECIO_COMPRA.HasValue ?
                new ObjectParameter("P_PRECIO_COMPRA", p_PRECIO_COMPRA) :
                new ObjectParameter("P_PRECIO_COMPRA", typeof(decimal));
    
            var p_PRECIO_VENTAParameter = p_PRECIO_VENTA.HasValue ?
                new ObjectParameter("P_PRECIO_VENTA", p_PRECIO_VENTA) :
                new ObjectParameter("P_PRECIO_VENTA", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_MARCAParameter = p_MARCA != null ?
                new ObjectParameter("P_MARCA", p_MARCA) :
                new ObjectParameter("P_MARCA", typeof(string));
    
            var p_CATEGORIAParameter = p_CATEGORIA != null ?
                new ObjectParameter("P_CATEGORIA", p_CATEGORIA) :
                new ObjectParameter("P_CATEGORIA", typeof(string));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(decimal));
    
            var p_FECHA_VENCIMIENTOParameter = p_FECHA_VENCIMIENTO.HasValue ?
                new ObjectParameter("P_FECHA_VENCIMIENTO", p_FECHA_VENCIMIENTO) :
                new ObjectParameter("P_FECHA_VENCIMIENTO", typeof(System.DateTime));
    
            var p_UNIDAD_DE_MEDIDA_IDParameter = p_UNIDAD_DE_MEDIDA_ID.HasValue ?
                new ObjectParameter("P_UNIDAD_DE_MEDIDA_ID", p_UNIDAD_DE_MEDIDA_ID) :
                new ObjectParameter("P_UNIDAD_DE_MEDIDA_ID", typeof(decimal));
    
            var p_TIPO_PRODUCTO_IDParameter = p_TIPO_PRODUCTO_ID.HasValue ?
                new ObjectParameter("P_TIPO_PRODUCTO_ID", p_TIPO_PRODUCTO_ID) :
                new ObjectParameter("P_TIPO_PRODUCTO_ID", typeof(decimal));
    
            var p_PROVEEDOR_IDParameter = p_PROVEEDOR_ID.HasValue ?
                new ObjectParameter("P_PROVEEDOR_ID", p_PROVEEDOR_ID) :
                new ObjectParameter("P_PROVEEDOR_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARPRODUCTO", p_ID_PRODUCTOParameter, p_DESCRIPCIONParameter, p_PRECIO_COMPRAParameter, p_PRECIO_VENTAParameter, p_NOMBREParameter, p_MARCAParameter, p_CATEGORIAParameter, p_STOCKParameter, p_FECHA_VENCIMIENTOParameter, p_UNIDAD_DE_MEDIDA_IDParameter, p_TIPO_PRODUCTO_IDParameter, p_PROVEEDOR_IDParameter);
        }
    
        public virtual int INSERTARPROVEEDOR(Nullable<decimal> p_ID, string p_NOMBRE, string p_EMAIL, string p_DIRECCION)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARPROVEEDOR", p_IDParameter, p_NOMBREParameter, p_EMAILParameter, p_DIRECCIONParameter);
        }
    
        public virtual int INSERTARPROVEEDOR2(string p_NOMBRE, string p_EMAIL, string p_DIRECCION)
        {
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARPROVEEDOR2", p_NOMBREParameter, p_EMAILParameter, p_DIRECCIONParameter);
        }
    
        public virtual int INSERTARRESERVA(Nullable<decimal> p_ID_RESERVA, string p_CODIGO_RESERVA, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_CANTIDAD_COMENSALES, string p_ESTADO_RESERVA, Nullable<decimal> p_USUARIO_ID_USUARIO, Nullable<decimal> p_USUARIO_ROL_ID_ROL, Nullable<decimal> p_MESA_ID_MESA)
        {
            var p_ID_RESERVAParameter = p_ID_RESERVA.HasValue ?
                new ObjectParameter("P_ID_RESERVA", p_ID_RESERVA) :
                new ObjectParameter("P_ID_RESERVA", typeof(decimal));
    
            var p_CODIGO_RESERVAParameter = p_CODIGO_RESERVA != null ?
                new ObjectParameter("P_CODIGO_RESERVA", p_CODIGO_RESERVA) :
                new ObjectParameter("P_CODIGO_RESERVA", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_CANTIDAD_COMENSALESParameter = p_CANTIDAD_COMENSALES.HasValue ?
                new ObjectParameter("P_CANTIDAD_COMENSALES", p_CANTIDAD_COMENSALES) :
                new ObjectParameter("P_CANTIDAD_COMENSALES", typeof(decimal));
    
            var p_ESTADO_RESERVAParameter = p_ESTADO_RESERVA != null ?
                new ObjectParameter("P_ESTADO_RESERVA", p_ESTADO_RESERVA) :
                new ObjectParameter("P_ESTADO_RESERVA", typeof(string));
    
            var p_USUARIO_ID_USUARIOParameter = p_USUARIO_ID_USUARIO.HasValue ?
                new ObjectParameter("P_USUARIO_ID_USUARIO", p_USUARIO_ID_USUARIO) :
                new ObjectParameter("P_USUARIO_ID_USUARIO", typeof(decimal));
    
            var p_USUARIO_ROL_ID_ROLParameter = p_USUARIO_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_USUARIO_ROL_ID_ROL", p_USUARIO_ROL_ID_ROL) :
                new ObjectParameter("P_USUARIO_ROL_ID_ROL", typeof(decimal));
    
            var p_MESA_ID_MESAParameter = p_MESA_ID_MESA.HasValue ?
                new ObjectParameter("P_MESA_ID_MESA", p_MESA_ID_MESA) :
                new ObjectParameter("P_MESA_ID_MESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARRESERVA", p_ID_RESERVAParameter, p_CODIGO_RESERVAParameter, p_FECHAParameter, p_CANTIDAD_COMENSALESParameter, p_ESTADO_RESERVAParameter, p_USUARIO_ID_USUARIOParameter, p_USUARIO_ROL_ID_ROLParameter, p_MESA_ID_MESAParameter);
        }
    
        public virtual int INSERTARUSUARIO(Nullable<decimal> p_ID_USUARIO, string p_CONTRASENA, string p_NOMBRE, string p_APELLIDO, string p_EMAIL, string p_DIRECCION, Nullable<decimal> p_ROL_ID_ROL, string p_GENERO, Nullable<decimal> p_ESTADO_USUARIO, string p_TELEFONO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ROL_ID_ROLParameter = p_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_ROL_ID_ROL", p_ROL_ID_ROL) :
                new ObjectParameter("P_ROL_ID_ROL", typeof(decimal));
    
            var p_GENEROParameter = p_GENERO != null ?
                new ObjectParameter("P_GENERO", p_GENERO) :
                new ObjectParameter("P_GENERO", typeof(string));
    
            var p_ESTADO_USUARIOParameter = p_ESTADO_USUARIO.HasValue ?
                new ObjectParameter("P_ESTADO_USUARIO", p_ESTADO_USUARIO) :
                new ObjectParameter("P_ESTADO_USUARIO", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARUSUARIO", p_ID_USUARIOParameter, p_CONTRASENAParameter, p_NOMBREParameter, p_APELLIDOParameter, p_EMAILParameter, p_DIRECCIONParameter, p_ROL_ID_ROLParameter, p_GENEROParameter, p_ESTADO_USUARIOParameter, p_TELEFONOParameter);
        }
    
        public virtual int INSERTARUSUARIO2(string p_CONTRASENA, string p_NOMBRE, string p_APELLIDO, string p_EMAIL, string p_DIRECCION, Nullable<decimal> p_ROL_ID_ROL, string p_GENERO, Nullable<decimal> p_ESTADO_USUARIO, string p_TELEFONO)
        {
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ROL_ID_ROLParameter = p_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_ROL_ID_ROL", p_ROL_ID_ROL) :
                new ObjectParameter("P_ROL_ID_ROL", typeof(decimal));
    
            var p_GENEROParameter = p_GENERO != null ?
                new ObjectParameter("P_GENERO", p_GENERO) :
                new ObjectParameter("P_GENERO", typeof(string));
    
            var p_ESTADO_USUARIOParameter = p_ESTADO_USUARIO.HasValue ?
                new ObjectParameter("P_ESTADO_USUARIO", p_ESTADO_USUARIO) :
                new ObjectParameter("P_ESTADO_USUARIO", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARUSUARIO2", p_CONTRASENAParameter, p_NOMBREParameter, p_APELLIDOParameter, p_EMAILParameter, p_DIRECCIONParameter, p_ROL_ID_ROLParameter, p_GENEROParameter, p_ESTADO_USUARIOParameter, p_TELEFONOParameter);
        }
    
        public virtual int INSERTARUSUARIO3(string p_CONTRASENA, string p_NOMBRE, string p_APELLIDO, string p_EMAIL, string p_DIRECCION, Nullable<decimal> p_ROL_ID_ROL, string p_GENERO, Nullable<decimal> p_ESTADO_USUARIO, string p_TELEFONO)
        {
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ROL_ID_ROLParameter = p_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_ROL_ID_ROL", p_ROL_ID_ROL) :
                new ObjectParameter("P_ROL_ID_ROL", typeof(decimal));
    
            var p_GENEROParameter = p_GENERO != null ?
                new ObjectParameter("P_GENERO", p_GENERO) :
                new ObjectParameter("P_GENERO", typeof(string));
    
            var p_ESTADO_USUARIOParameter = p_ESTADO_USUARIO.HasValue ?
                new ObjectParameter("P_ESTADO_USUARIO", p_ESTADO_USUARIO) :
                new ObjectParameter("P_ESTADO_USUARIO", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("INSERTARUSUARIO3", p_CONTRASENAParameter, p_NOMBREParameter, p_APELLIDOParameter, p_EMAILParameter, p_DIRECCIONParameter, p_ROL_ID_ROLParameter, p_GENEROParameter, p_ESTADO_USUARIOParameter, p_TELEFONOParameter);
        }
    
        public virtual int LISTARMENUS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARMENUS");
        }
    
        public virtual int LISTARMESAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARMESAS");
        }
    
        public virtual int LISTARPAGOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARPAGOS");
        }
    
        public virtual int LISTARPRODUCTOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARPRODUCTOS");
        }
    
        public virtual int LISTARPROVEEDORES()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARPROVEEDORES");
        }
    
        public virtual int LISTARRECETAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARRECETAS");
        }
    
        public virtual int LISTARRESERVAS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARRESERVAS");
        }
    
        public virtual int LISTARUSUARIOS()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("LISTARUSUARIOS");
        }
    
        public virtual int MODIFICARESTADOPEDIDO(Nullable<decimal> p_PEDIDO_ID_PEDIDO, Nullable<decimal> p_EST_PEDIDO_ID_EST_PEDIDO)
        {
            var p_PEDIDO_ID_PEDIDOParameter = p_PEDIDO_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", p_PEDIDO_ID_PEDIDO) :
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", typeof(decimal));
    
            var p_EST_PEDIDO_ID_EST_PEDIDOParameter = p_EST_PEDIDO_ID_EST_PEDIDO.HasValue ?
                new ObjectParameter("P_EST_PEDIDO_ID_EST_PEDIDO", p_EST_PEDIDO_ID_EST_PEDIDO) :
                new ObjectParameter("P_EST_PEDIDO_ID_EST_PEDIDO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARESTADOPEDIDO", p_PEDIDO_ID_PEDIDOParameter, p_EST_PEDIDO_ID_EST_PEDIDOParameter);
        }
    
        public virtual int MODIFICARMENU(Nullable<decimal> p_ID_MENU, string p_CODIGO_MENU, string p_NOMBRE, Nullable<decimal> p_PRECIO, byte[] p_FOTO, Nullable<decimal> p_DISPONIBLE, Nullable<decimal> p_TIPO_MENU_ID)
        {
            var p_ID_MENUParameter = p_ID_MENU.HasValue ?
                new ObjectParameter("P_ID_MENU", p_ID_MENU) :
                new ObjectParameter("P_ID_MENU", typeof(decimal));
    
            var p_CODIGO_MENUParameter = p_CODIGO_MENU != null ?
                new ObjectParameter("P_CODIGO_MENU", p_CODIGO_MENU) :
                new ObjectParameter("P_CODIGO_MENU", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            var p_FOTOParameter = p_FOTO != null ?
                new ObjectParameter("P_FOTO", p_FOTO) :
                new ObjectParameter("P_FOTO", typeof(byte[]));
    
            var p_DISPONIBLEParameter = p_DISPONIBLE.HasValue ?
                new ObjectParameter("P_DISPONIBLE", p_DISPONIBLE) :
                new ObjectParameter("P_DISPONIBLE", typeof(decimal));
    
            var p_TIPO_MENU_IDParameter = p_TIPO_MENU_ID.HasValue ?
                new ObjectParameter("P_TIPO_MENU_ID", p_TIPO_MENU_ID) :
                new ObjectParameter("P_TIPO_MENU_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARMENU", p_ID_MENUParameter, p_CODIGO_MENUParameter, p_NOMBREParameter, p_PRECIOParameter, p_FOTOParameter, p_DISPONIBLEParameter, p_TIPO_MENU_IDParameter);
        }
    
        public virtual int MODIFICARMESA(Nullable<decimal> p_ID_MESA, Nullable<decimal> p_NUMERO_MESA, Nullable<decimal> p_CAPACIDAD, string p_DESCRIPCION, string p_EN_USO, string p_ACTIVA)
        {
            var p_ID_MESAParameter = p_ID_MESA.HasValue ?
                new ObjectParameter("P_ID_MESA", p_ID_MESA) :
                new ObjectParameter("P_ID_MESA", typeof(decimal));
    
            var p_NUMERO_MESAParameter = p_NUMERO_MESA.HasValue ?
                new ObjectParameter("P_NUMERO_MESA", p_NUMERO_MESA) :
                new ObjectParameter("P_NUMERO_MESA", typeof(decimal));
    
            var p_CAPACIDADParameter = p_CAPACIDAD.HasValue ?
                new ObjectParameter("P_CAPACIDAD", p_CAPACIDAD) :
                new ObjectParameter("P_CAPACIDAD", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_EN_USOParameter = p_EN_USO != null ?
                new ObjectParameter("P_EN_USO", p_EN_USO) :
                new ObjectParameter("P_EN_USO", typeof(string));
    
            var p_ACTIVAParameter = p_ACTIVA != null ?
                new ObjectParameter("P_ACTIVA", p_ACTIVA) :
                new ObjectParameter("P_ACTIVA", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARMESA", p_ID_MESAParameter, p_NUMERO_MESAParameter, p_CAPACIDADParameter, p_DESCRIPCIONParameter, p_EN_USOParameter, p_ACTIVAParameter);
        }
    
        public virtual int MODIFICARPAGO(Nullable<decimal> p_ID_PAGO, Nullable<System.DateTime> p_FECHA_PAGO, string p_URL, string p_TOKEN, Nullable<decimal> p_ORDEN_PAGO, Nullable<decimal> p_TIPO_DE_PAGO_ID_TIPO_PAGO, Nullable<decimal> p_PEDIDO_ID_PEDIDO, Nullable<decimal> p_CUOTAS)
        {
            var p_ID_PAGOParameter = p_ID_PAGO.HasValue ?
                new ObjectParameter("P_ID_PAGO", p_ID_PAGO) :
                new ObjectParameter("P_ID_PAGO", typeof(decimal));
    
            var p_FECHA_PAGOParameter = p_FECHA_PAGO.HasValue ?
                new ObjectParameter("P_FECHA_PAGO", p_FECHA_PAGO) :
                new ObjectParameter("P_FECHA_PAGO", typeof(System.DateTime));
    
            var p_URLParameter = p_URL != null ?
                new ObjectParameter("P_URL", p_URL) :
                new ObjectParameter("P_URL", typeof(string));
    
            var p_TOKENParameter = p_TOKEN != null ?
                new ObjectParameter("P_TOKEN", p_TOKEN) :
                new ObjectParameter("P_TOKEN", typeof(string));
    
            var p_ORDEN_PAGOParameter = p_ORDEN_PAGO.HasValue ?
                new ObjectParameter("P_ORDEN_PAGO", p_ORDEN_PAGO) :
                new ObjectParameter("P_ORDEN_PAGO", typeof(decimal));
    
            var p_TIPO_DE_PAGO_ID_TIPO_PAGOParameter = p_TIPO_DE_PAGO_ID_TIPO_PAGO.HasValue ?
                new ObjectParameter("P_TIPO_DE_PAGO_ID_TIPO_PAGO", p_TIPO_DE_PAGO_ID_TIPO_PAGO) :
                new ObjectParameter("P_TIPO_DE_PAGO_ID_TIPO_PAGO", typeof(decimal));
    
            var p_PEDIDO_ID_PEDIDOParameter = p_PEDIDO_ID_PEDIDO.HasValue ?
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", p_PEDIDO_ID_PEDIDO) :
                new ObjectParameter("P_PEDIDO_ID_PEDIDO", typeof(decimal));
    
            var p_CUOTASParameter = p_CUOTAS.HasValue ?
                new ObjectParameter("P_CUOTAS", p_CUOTAS) :
                new ObjectParameter("P_CUOTAS", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARPAGO", p_ID_PAGOParameter, p_FECHA_PAGOParameter, p_URLParameter, p_TOKENParameter, p_ORDEN_PAGOParameter, p_TIPO_DE_PAGO_ID_TIPO_PAGOParameter, p_PEDIDO_ID_PEDIDOParameter, p_CUOTASParameter);
        }
    
        public virtual int MODIFICARPRODUCTO(Nullable<decimal> p_ID_PRODUCTO, string p_DESCRIPCION, Nullable<decimal> p_PRECIO_COMPRA, Nullable<decimal> p_PRECIO_VENTA, string p_NOMBRE, string p_MARCA, string p_CATEGORIA, Nullable<decimal> p_STOCK, Nullable<System.DateTime> p_FECHA_VENCIMIENTO, Nullable<decimal> p_UNIDAD_DE_MEDIDA_ID, Nullable<decimal> p_TIPO_PRODUCTO_ID, Nullable<decimal> p_PROVEEDOR_ID)
        {
            var p_ID_PRODUCTOParameter = p_ID_PRODUCTO.HasValue ?
                new ObjectParameter("P_ID_PRODUCTO", p_ID_PRODUCTO) :
                new ObjectParameter("P_ID_PRODUCTO", typeof(decimal));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_PRECIO_COMPRAParameter = p_PRECIO_COMPRA.HasValue ?
                new ObjectParameter("P_PRECIO_COMPRA", p_PRECIO_COMPRA) :
                new ObjectParameter("P_PRECIO_COMPRA", typeof(decimal));
    
            var p_PRECIO_VENTAParameter = p_PRECIO_VENTA.HasValue ?
                new ObjectParameter("P_PRECIO_VENTA", p_PRECIO_VENTA) :
                new ObjectParameter("P_PRECIO_VENTA", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_MARCAParameter = p_MARCA != null ?
                new ObjectParameter("P_MARCA", p_MARCA) :
                new ObjectParameter("P_MARCA", typeof(string));
    
            var p_CATEGORIAParameter = p_CATEGORIA != null ?
                new ObjectParameter("P_CATEGORIA", p_CATEGORIA) :
                new ObjectParameter("P_CATEGORIA", typeof(string));
    
            var p_STOCKParameter = p_STOCK.HasValue ?
                new ObjectParameter("P_STOCK", p_STOCK) :
                new ObjectParameter("P_STOCK", typeof(decimal));
    
            var p_FECHA_VENCIMIENTOParameter = p_FECHA_VENCIMIENTO.HasValue ?
                new ObjectParameter("P_FECHA_VENCIMIENTO", p_FECHA_VENCIMIENTO) :
                new ObjectParameter("P_FECHA_VENCIMIENTO", typeof(System.DateTime));
    
            var p_UNIDAD_DE_MEDIDA_IDParameter = p_UNIDAD_DE_MEDIDA_ID.HasValue ?
                new ObjectParameter("P_UNIDAD_DE_MEDIDA_ID", p_UNIDAD_DE_MEDIDA_ID) :
                new ObjectParameter("P_UNIDAD_DE_MEDIDA_ID", typeof(decimal));
    
            var p_TIPO_PRODUCTO_IDParameter = p_TIPO_PRODUCTO_ID.HasValue ?
                new ObjectParameter("P_TIPO_PRODUCTO_ID", p_TIPO_PRODUCTO_ID) :
                new ObjectParameter("P_TIPO_PRODUCTO_ID", typeof(decimal));
    
            var p_PROVEEDOR_IDParameter = p_PROVEEDOR_ID.HasValue ?
                new ObjectParameter("P_PROVEEDOR_ID", p_PROVEEDOR_ID) :
                new ObjectParameter("P_PROVEEDOR_ID", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARPRODUCTO", p_ID_PRODUCTOParameter, p_DESCRIPCIONParameter, p_PRECIO_COMPRAParameter, p_PRECIO_VENTAParameter, p_NOMBREParameter, p_MARCAParameter, p_CATEGORIAParameter, p_STOCKParameter, p_FECHA_VENCIMIENTOParameter, p_UNIDAD_DE_MEDIDA_IDParameter, p_TIPO_PRODUCTO_IDParameter, p_PROVEEDOR_IDParameter);
        }
    
        public virtual int MODIFICARPROVEEDOR(Nullable<decimal> p_ID, string p_NOMBRE, string p_EMAIL, string p_DIRECCION)
        {
            var p_IDParameter = p_ID.HasValue ?
                new ObjectParameter("P_ID", p_ID) :
                new ObjectParameter("P_ID", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARPROVEEDOR", p_IDParameter, p_NOMBREParameter, p_EMAILParameter, p_DIRECCIONParameter);
        }
    
        public virtual int MODIFICARRECETA(Nullable<decimal> p_ID_RECETA, string p_NOMBRE, string p_DESCRIPCION, Nullable<decimal> p_TIEMPO_PREPARACION, Nullable<decimal> p_PRECIO)
        {
            var p_ID_RECETAParameter = p_ID_RECETA.HasValue ?
                new ObjectParameter("P_ID_RECETA", p_ID_RECETA) :
                new ObjectParameter("P_ID_RECETA", typeof(decimal));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_DESCRIPCIONParameter = p_DESCRIPCION != null ?
                new ObjectParameter("P_DESCRIPCION", p_DESCRIPCION) :
                new ObjectParameter("P_DESCRIPCION", typeof(string));
    
            var p_TIEMPO_PREPARACIONParameter = p_TIEMPO_PREPARACION.HasValue ?
                new ObjectParameter("P_TIEMPO_PREPARACION", p_TIEMPO_PREPARACION) :
                new ObjectParameter("P_TIEMPO_PREPARACION", typeof(decimal));
    
            var p_PRECIOParameter = p_PRECIO.HasValue ?
                new ObjectParameter("P_PRECIO", p_PRECIO) :
                new ObjectParameter("P_PRECIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARRECETA", p_ID_RECETAParameter, p_NOMBREParameter, p_DESCRIPCIONParameter, p_TIEMPO_PREPARACIONParameter, p_PRECIOParameter);
        }
    
        public virtual int MODIFICARRESERVA(Nullable<decimal> p_ID_RESERVA, string p_CODIGO_RESERVA, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_CANTIDAD_COMENSALES, string p_ESTADO_RESERVA, Nullable<decimal> p_USUARIO_ID_USUARIO, Nullable<decimal> p_USUARIO_ROL_ID_ROL, Nullable<decimal> p_MESA_ID_MESA)
        {
            var p_ID_RESERVAParameter = p_ID_RESERVA.HasValue ?
                new ObjectParameter("P_ID_RESERVA", p_ID_RESERVA) :
                new ObjectParameter("P_ID_RESERVA", typeof(decimal));
    
            var p_CODIGO_RESERVAParameter = p_CODIGO_RESERVA != null ?
                new ObjectParameter("P_CODIGO_RESERVA", p_CODIGO_RESERVA) :
                new ObjectParameter("P_CODIGO_RESERVA", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_CANTIDAD_COMENSALESParameter = p_CANTIDAD_COMENSALES.HasValue ?
                new ObjectParameter("P_CANTIDAD_COMENSALES", p_CANTIDAD_COMENSALES) :
                new ObjectParameter("P_CANTIDAD_COMENSALES", typeof(decimal));
    
            var p_ESTADO_RESERVAParameter = p_ESTADO_RESERVA != null ?
                new ObjectParameter("P_ESTADO_RESERVA", p_ESTADO_RESERVA) :
                new ObjectParameter("P_ESTADO_RESERVA", typeof(string));
    
            var p_USUARIO_ID_USUARIOParameter = p_USUARIO_ID_USUARIO.HasValue ?
                new ObjectParameter("P_USUARIO_ID_USUARIO", p_USUARIO_ID_USUARIO) :
                new ObjectParameter("P_USUARIO_ID_USUARIO", typeof(decimal));
    
            var p_USUARIO_ROL_ID_ROLParameter = p_USUARIO_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_USUARIO_ROL_ID_ROL", p_USUARIO_ROL_ID_ROL) :
                new ObjectParameter("P_USUARIO_ROL_ID_ROL", typeof(decimal));
    
            var p_MESA_ID_MESAParameter = p_MESA_ID_MESA.HasValue ?
                new ObjectParameter("P_MESA_ID_MESA", p_MESA_ID_MESA) :
                new ObjectParameter("P_MESA_ID_MESA", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARRESERVA", p_ID_RESERVAParameter, p_CODIGO_RESERVAParameter, p_FECHAParameter, p_CANTIDAD_COMENSALESParameter, p_ESTADO_RESERVAParameter, p_USUARIO_ID_USUARIOParameter, p_USUARIO_ROL_ID_ROLParameter, p_MESA_ID_MESAParameter);
        }
    
        public virtual int MODIFICARUSUARIO(Nullable<decimal> p_ID_USUARIO, string p_CONTRASENA, string p_NOMBRE, string p_APELLIDO, string p_EMAIL, string p_DIRECCION, Nullable<decimal> p_ROL_ID_ROL, string p_GENERO, Nullable<decimal> p_ESTADO_USUARIO, string p_TELEFONO)
        {
            var p_ID_USUARIOParameter = p_ID_USUARIO.HasValue ?
                new ObjectParameter("P_ID_USUARIO", p_ID_USUARIO) :
                new ObjectParameter("P_ID_USUARIO", typeof(decimal));
    
            var p_CONTRASENAParameter = p_CONTRASENA != null ?
                new ObjectParameter("P_CONTRASENA", p_CONTRASENA) :
                new ObjectParameter("P_CONTRASENA", typeof(string));
    
            var p_NOMBREParameter = p_NOMBRE != null ?
                new ObjectParameter("P_NOMBRE", p_NOMBRE) :
                new ObjectParameter("P_NOMBRE", typeof(string));
    
            var p_APELLIDOParameter = p_APELLIDO != null ?
                new ObjectParameter("P_APELLIDO", p_APELLIDO) :
                new ObjectParameter("P_APELLIDO", typeof(string));
    
            var p_EMAILParameter = p_EMAIL != null ?
                new ObjectParameter("P_EMAIL", p_EMAIL) :
                new ObjectParameter("P_EMAIL", typeof(string));
    
            var p_DIRECCIONParameter = p_DIRECCION != null ?
                new ObjectParameter("P_DIRECCION", p_DIRECCION) :
                new ObjectParameter("P_DIRECCION", typeof(string));
    
            var p_ROL_ID_ROLParameter = p_ROL_ID_ROL.HasValue ?
                new ObjectParameter("P_ROL_ID_ROL", p_ROL_ID_ROL) :
                new ObjectParameter("P_ROL_ID_ROL", typeof(decimal));
    
            var p_GENEROParameter = p_GENERO != null ?
                new ObjectParameter("P_GENERO", p_GENERO) :
                new ObjectParameter("P_GENERO", typeof(string));
    
            var p_ESTADO_USUARIOParameter = p_ESTADO_USUARIO.HasValue ?
                new ObjectParameter("P_ESTADO_USUARIO", p_ESTADO_USUARIO) :
                new ObjectParameter("P_ESTADO_USUARIO", typeof(decimal));
    
            var p_TELEFONOParameter = p_TELEFONO != null ?
                new ObjectParameter("P_TELEFONO", p_TELEFONO) :
                new ObjectParameter("P_TELEFONO", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("MODIFICARUSUARIO", p_ID_USUARIOParameter, p_CONTRASENAParameter, p_NOMBREParameter, p_APELLIDOParameter, p_EMAILParameter, p_DIRECCIONParameter, p_ROL_ID_ROLParameter, p_GENEROParameter, p_ESTADO_USUARIOParameter, p_TELEFONOParameter);
        }
    
        public virtual int PRODUCTOSTOP()
        {
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("PRODUCTOSTOP");
        }
    
        public virtual int REALIZARRESERVA(string p_CODIGO_RESERVA, Nullable<System.DateTime> p_FECHA, Nullable<decimal> p_CANTIDAD_COMENSALES, Nullable<decimal> p_USUARIO_ID_USUARIO)
        {
            var p_CODIGO_RESERVAParameter = p_CODIGO_RESERVA != null ?
                new ObjectParameter("P_CODIGO_RESERVA", p_CODIGO_RESERVA) :
                new ObjectParameter("P_CODIGO_RESERVA", typeof(string));
    
            var p_FECHAParameter = p_FECHA.HasValue ?
                new ObjectParameter("P_FECHA", p_FECHA) :
                new ObjectParameter("P_FECHA", typeof(System.DateTime));
    
            var p_CANTIDAD_COMENSALESParameter = p_CANTIDAD_COMENSALES.HasValue ?
                new ObjectParameter("P_CANTIDAD_COMENSALES", p_CANTIDAD_COMENSALES) :
                new ObjectParameter("P_CANTIDAD_COMENSALES", typeof(decimal));
    
            var p_USUARIO_ID_USUARIOParameter = p_USUARIO_ID_USUARIO.HasValue ?
                new ObjectParameter("P_USUARIO_ID_USUARIO", p_USUARIO_ID_USUARIO) :
                new ObjectParameter("P_USUARIO_ID_USUARIO", typeof(decimal));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("REALIZARRESERVA", p_CODIGO_RESERVAParameter, p_FECHAParameter, p_CANTIDAD_COMENSALESParameter, p_USUARIO_ID_USUARIOParameter);
        }
    }
}
