//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class PAGO
    {
        public decimal ID_PAGO { get; set; }
        public Nullable<System.DateTime> FECHA_PAGO { get; set; }
        public string URL { get; set; }
        public string TOKEN { get; set; }
        public Nullable<decimal> ORDEN_PAGO { get; set; }
        public decimal TIPO_DE_PAGO_ID_TIPO_PAGO { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
        public Nullable<decimal> CUOTAS { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual TIPO_DE_PAGO TIPO_DE_PAGO { get; set; }
    }
}
