//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class USUARIO_PEDIDO
    {
        public string COMENTARIO_ESPECIAL { get; set; }
        public decimal USUARIO_ID_USUARIO { get; set; }
        public decimal USUARIO_ROL_ID_ROL { get; set; }
        public decimal PEDIDO_ID_PEDIDO { get; set; }
    
        public virtual PEDIDO PEDIDO { get; set; }
        public virtual USUARIO USUARIO { get; set; }
    }
}
